USE [STUDMANBORROMEE]
GO

/****** Object:  Table [dbo].[T_Annee]    Script Date: 09/03/2022 16:01:10 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[T_Annee](
	[CodeAnnee] [char](10) NOT NULL,
	[Libelle] [char](10) NULL,
 CONSTRAINT [PK_T_Année] PRIMARY KEY CLUSTERED 
(
	[CodeAnnee] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


