USE [STUDMANBORROMEE]
GO

/****** Object:  Table [dbo].[t_tranche]    Script Date: 09/03/2022 16:37:43 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[t_tranche](
	[code] [char](10) NOT NULL,
	[libellet] [char](30) NULL,
 CONSTRAINT [PK_t_tranche] PRIMARY KEY CLUSTERED 
(
	[code] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


